// Copyright 2026 - See NOTICE file for copyright holders.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Command aggregate reads the per-run JSONL records emitted by the instrumented
// scenarios (bench/results/*.jsonl) and writes a single Markdown report
// (bench/results/tables.md) with one set of tables per thesis scenario: on-chain
// cost (ETH gas / CKB cycles), settlement latency, state versions (with the I1 /
// I1* invariant checks), configuration constants, and balance net-change. Each
// numeric row reports median | min | max | std-dev | N, per the Chapter 9
// handover's Output Format. Stdlib-only; run from the repo root:
//
//	go run ./bench/aggregate            # reads ./bench/results, writes tables.md
//	go run ./bench/aggregate <dir> <out.md>
package main

import (
	"encoding/json"
	"fmt"
	"math"
	"math/big"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type ethTx struct {
	Label    string `json:"label"`
	GasUsed  uint64 `json:"gasUsed"`
	CallData int    `json:"callData"`
}

type ckbTx struct {
	Label  string `json:"label"`
	Cycles uint64 `json:"cycles"`
}

type record struct {
	Scenario string             `json:"scenario"`
	Mode     string             `json:"mode"`
	ThesisSc string             `json:"thesisSc"`
	Run      int                `json:"run"`
	OK       bool               `json:"ok"`
	Outcome  string             `json:"outcome"`
	ETH      []ethTx            `json:"eth"`
	CKB      []ckbTx            `json:"ckb"`
	Phases   map[string]float64 `json:"phases"`
	Versions map[string]uint64  `json:"versions"`
	Balances map[string]string  `json:"balances"`
	Config   map[string]any     `json:"config"`
}

// group collects all records for one (scenario, mode).
type group struct {
	key      string
	scenario string
	mode     string
	thesisSc string
	recs     []record
}

func main() {
	dir := "bench/results"
	out := "bench/results/tables.md"
	if len(os.Args) > 1 {
		dir = os.Args[1]
	}
	if len(os.Args) > 2 {
		out = os.Args[2]
	}

	files, _ := filepath.Glob(filepath.Join(dir, "*.jsonl"))
	if len(files) == 0 {
		fmt.Fprintf(os.Stderr, "no *.jsonl files in %s\n", dir)
		os.Exit(1)
	}

	groups := map[string]*group{}
	var order []string
	for _, f := range files {
		data, err := os.ReadFile(f)
		if err != nil {
			fmt.Fprintf(os.Stderr, "read %s: %v\n", f, err)
			continue
		}
		for _, line := range strings.Split(string(data), "\n") {
			line = strings.TrimSpace(line)
			if line == "" {
				continue
			}
			var r record
			if err := json.Unmarshal([]byte(line), &r); err != nil {
				fmt.Fprintf(os.Stderr, "parse line in %s: %v\n", f, err)
				continue
			}
			if !r.OK {
				continue
			}
			k := r.Scenario + "|" + r.Mode
			g, ok := groups[k]
			if !ok {
				g = &group{key: k, scenario: r.Scenario, mode: r.Mode, thesisSc: r.ThesisSc}
				groups[k] = g
				order = append(order, k)
			}
			g.recs = append(g.recs, r)
		}
	}

	// Order groups by thesis scenario id, then key.
	sort.Slice(order, func(i, j int) bool {
		gi, gj := groups[order[i]], groups[order[j]]
		if gi.thesisSc != gj.thesisSc {
			return gi.thesisSc < gj.thesisSc
		}
		return order[i] < order[j]
	})

	var b strings.Builder
	b.WriteString("# Evaluation results — aggregated\n\n")
	b.WriteString("Generated by `bench/aggregate` from `bench/results/*.jsonl`. ")
	b.WriteString("Numeric rows: `median | min | max | std-dev | N`. ")
	b.WriteString("Gas/cycles are summed per phase per run, then aggregated across runs.\n")

	for _, k := range order {
		writeGroup(&b, groups[k])
	}

	if err := os.WriteFile(out, []byte(b.String()), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "write %s: %v\n", out, err)
		os.Exit(1)
	}
	fmt.Printf("wrote %s (%d scenario groups)\n", out, len(order))
}

func writeGroup(b *strings.Builder, g *group) {
	n := len(g.recs)
	title := g.thesisSc
	if title == "" {
		title = "—"
	}
	fmt.Fprintf(b, "\n---\n\n## %s — `%s -mode=%s`  (N=%d)\n\n", title, g.scenario, g.mode, n)
	if n == 0 {
		b.WriteString("_No successful runs._\n")
		return
	}

	// ---- Cost: ETH gas per phase ----
	ethLabels, ethVals := sumByLabelETH(g.recs)
	if len(ethLabels) > 0 {
		b.WriteString("### On-chain cost — Ethereum gas (per phase, summed)\n\n")
		writeStatTable(b, "phase", ethLabels, ethVals)
	}

	// ---- Cost: CKB cycles per phase ----
	ckbLabels, ckbVals := sumByLabelCKB(g.recs)
	if len(ckbLabels) > 0 {
		b.WriteString("\n### On-chain cost — CKB cycles (per phase, summed)\n\n")
		writeStatTable(b, "phase", ckbLabels, ckbVals)
	}

	// ---- Latency per phase ----
	phLabels, phVals := byLabelFloat(g.recs)
	if len(phLabels) > 0 {
		b.WriteString("\n### Settlement latency (ms, per phase)\n\n")
		writeStatTable(b, "phase", phLabels, phVals)
	}

	// ---- State versions + invariants ----
	writeVersions(b, g.recs)

	// ---- Config (Group D) ----
	writeConfig(b, g.recs)

	// ---- Balance net change ----
	writeBalances(b, g.recs)
}

// ---------- aggregation helpers ----------

func sumByLabelETH(recs []record) ([]string, map[string][]float64) {
	vals := map[string][]float64{}
	for _, r := range recs {
		per := map[string]uint64{}
		for _, t := range r.ETH {
			per[t.Label] += t.GasUsed
		}
		for l, v := range per {
			vals[l] = append(vals[l], float64(v))
		}
	}
	return sortedKeys(vals), vals
}

func sumByLabelCKB(recs []record) ([]string, map[string][]float64) {
	vals := map[string][]float64{}
	for _, r := range recs {
		per := map[string]uint64{}
		for _, t := range r.CKB {
			per[t.Label] += t.Cycles
		}
		for l, v := range per {
			vals[l] = append(vals[l], float64(v))
		}
	}
	return sortedKeys(vals), vals
}

func byLabelFloat(recs []record) ([]string, map[string][]float64) {
	vals := map[string][]float64{}
	for _, r := range recs {
		for l, v := range r.Phases {
			vals[l] = append(vals[l], v)
		}
	}
	return sortedKeys(vals), vals
}

func writeVersions(b *strings.Builder, recs []record) {
	// Versions are deterministic per scenario; report the modal value per key.
	keys := map[string]bool{}
	for _, r := range recs {
		for k := range r.Versions {
			keys[k] = true
		}
	}
	if len(keys) == 0 {
		return
	}
	b.WriteString("\n### State versions (Group C)\n\n")
	b.WriteString("| key | version |\n|---|---|\n")
	mode := func(key string) (uint64, bool) {
		counts := map[uint64]int{}
		var any bool
		for _, r := range recs {
			if v, ok := r.Versions[key]; ok {
				counts[v]++
				any = true
			}
		}
		var best uint64
		var bc int
		for v, c := range counts {
			if c > bc {
				best, bc = v, c
			}
		}
		return best, any
	}
	for _, k := range sortedKeyset(keys) {
		if v, ok := mode(k); ok {
			fmt.Fprintf(b, "| %s | %d |\n", k, v)
		}
	}
	// Invariant checks.
	rc, rcok := mode("register_ckb")
	re, reok := mode("register_eth")
	if rcok && reok {
		i1 := "consistent (v_ckb == v_eth)"
		if rc != re {
			i1 = "VIOLATED (v_ckb != v_eth)"
		}
		cc, ccok := mode("conclude_ckb")
		ce, ceok := mode("conclude_eth")
		concl := ""
		if ccok && ceok {
			if cc == ce {
				concl = " — conclude: consistent"
			} else {
				concl = " — conclude: VIOLATED"
			}
		}
		fmt.Fprintf(b, "\n**I1 (register):** %s%s\n", i1, concl)
	}
}

func writeConfig(b *strings.Builder, recs []record) {
	merged := map[string]any{}
	for _, r := range recs {
		for k, v := range r.Config {
			if _, ok := merged[k]; !ok {
				merged[k] = v
			}
		}
	}
	if len(merged) == 0 {
		return
	}
	b.WriteString("\n### Configuration (Group D)\n\n")
	b.WriteString("| key | value |\n|---|---|\n")
	for _, k := range sortedKeysAny(merged) {
		fmt.Fprintf(b, "| %s | %s |\n", k, formatAny(merged[k]))
	}
}

// formatAny renders a config value, printing whole-number floats (JSON decodes
// all numbers to float64) as integers rather than scientific notation.
func formatAny(v any) string {
	if f, ok := v.(float64); ok && f == math.Trunc(f) && math.Abs(f) < 1e18 {
		return fmt.Sprintf("%d", int64(f))
	}
	return fmt.Sprintf("%v", v)
}

func writeBalances(b *strings.Builder, recs []record) {
	// Net change = post - pre, per "<party>_<chain>". CKB is cell capacity
	// (shannons); ETH is native wei and includes gas, so its net is not exactly
	// the channel delta.
	parties := map[string]bool{}
	for _, r := range recs {
		for k := range r.Balances {
			if strings.HasSuffix(k, "_pre") {
				parties[strings.TrimSuffix(k, "_pre")] = true
			}
		}
	}
	if len(parties) == 0 {
		return
	}
	b.WriteString("\n### Balance net change (post − pre; ETH wei incl. gas, CKB shannons)\n\n")
	b.WriteString("| account | median Δ | N |\n|---|---:|---:|\n")
	for _, p := range sortedKeyset(parties) {
		var deltas []float64
		var bigDeltas []*big.Int
		for _, r := range recs {
			pre, okp := r.Balances[p+"_pre"]
			post, okq := r.Balances[p+"_post"]
			if !okp || !okq {
				continue
			}
			a, ok1 := new(big.Int).SetString(pre, 10)
			c, ok2 := new(big.Int).SetString(post, 10)
			if !ok1 || !ok2 {
				continue
			}
			d := new(big.Int).Sub(c, a)
			bigDeltas = append(bigDeltas, d)
			fd := new(big.Float).SetInt(d)
			f, _ := fd.Float64()
			deltas = append(deltas, f)
		}
		if len(bigDeltas) == 0 {
			continue
		}
		med := medianBig(bigDeltas)
		fmt.Fprintf(b, "| %s | %s | %d |\n", p, med.String(), len(bigDeltas))
	}
}

// ---------- stats ----------

func writeStatTable(b *strings.Builder, head string, labels []string, vals map[string][]float64) {
	fmt.Fprintf(b, "| %s | median | min | max | std-dev | N |\n|---|---:|---:|---:|---:|---:|\n", head)
	for _, l := range labels {
		v := vals[l]
		md, mn, mx, sd := stats(v)
		fmt.Fprintf(b, "| %s | %s | %s | %s | %s | %d |\n", l, num(md), num(mn), num(mx), num(sd), len(v))
	}
}

func stats(v []float64) (median, min, max, std float64) {
	if len(v) == 0 {
		return 0, 0, 0, 0
	}
	s := append([]float64(nil), v...)
	sort.Float64s(s)
	min, max = s[0], s[len(s)-1]
	median = s[len(s)/2]
	if len(s)%2 == 0 {
		median = (s[len(s)/2-1] + s[len(s)/2]) / 2
	}
	var mean float64
	for _, x := range s {
		mean += x
	}
	mean /= float64(len(s))
	var sumsq float64
	for _, x := range s {
		sumsq += (x - mean) * (x - mean)
	}
	std = math.Sqrt(sumsq / float64(len(s)))
	return median, min, max, std
}

func medianBig(v []*big.Int) *big.Int {
	s := append([]*big.Int(nil), v...)
	sort.Slice(s, func(i, j int) bool { return s[i].Cmp(s[j]) < 0 })
	return s[len(s)/2]
}

func num(f float64) string {
	if f == math.Trunc(f) && math.Abs(f) < 1e15 {
		return fmt.Sprintf("%d", int64(f))
	}
	return fmt.Sprintf("%.1f", f)
}

func sortedKeys(m map[string][]float64) []string {
	ks := make([]string, 0, len(m))
	for k := range m {
		ks = append(ks, k)
	}
	sort.Strings(ks)
	return ks
}

func sortedKeyset(m map[string]bool) []string {
	ks := make([]string, 0, len(m))
	for k := range m {
		ks = append(ks, k)
	}
	sort.Strings(ks)
	return ks
}

func sortedKeysAny(m map[string]any) []string {
	ks := make([]string, 0, len(m))
	for k := range m {
		ks = append(ks, k)
	}
	sort.Strings(ks)
	return ks
}
